- shell:
        - [/bin/sh configs/nvim/install.sh]

- link:
        ~/.eslintrc.json: configs/nvim/.eslintrc.json
        ~/.tern-config: configs/nvim/.tern-config
        ~/.config/nvim/init.vim: configs/nvim/init.vim
